Remove timezone from Users and Organizations page
zendesk/volunteer_portal pull request #108
Opened 2018-11-19 08:25 UTC by dineshsaravanan

## Description
The Users and the Organizations tables in the admin pages have Timezone column, but data for them don't have that field. This PR removes the Timezone column.

Additionally, this PR adds Description, Website and Location columns to Organizations table. It also adds Email and Admin columns to the Users Table

## References
Fixes [organisation & users section have time zone header](https://github.com/zendesk/volunteer_portal/issues/77)

## Screenshots (if needed)
**Before:**
![image](https://user-images.githubusercontent.com/1055079/48694463-54729b00-ec17-11e8-97f5-f994d110d021.png)
**After:**
![image](https://user-images.githubusercontent.com/1055079/48694525-808e1c00-ec17-11e8-9cc1-7c1afb6f7506.png)

## CCs
@blakegong @rshokrizadeh @shiyunl 

## Risks (if any)
* [low] - Users and Organizations Admin View could be broken

2018-11-20 08:35 UTC, blakegong approved these changes

2018-11-20 20:44 UTC, craig-day requested changes
Can we also get screenshots of the users page?

2018-11-20 20:44 UTC, craig-day commented on app/javascript/pages/admin/Organizations/index.js
> +    websiteUrl = 'http://' + websiteUrl
I would rather have the server ensure a valid URL gets served. Maybe we put a validator on the organization model and a handler to return a nice and correctly formatted URL.

2019-01-17 07:07 UTC, craig-day commented
Is this still desired? If so, please resolve the conflicts. If not, please close this PR.

2019-05-22 06:32 UTC, xuebingli commented
Superseded by #159

2019-05-22 06:32 UTC, closed without merging