Create new event type if doesn't exist before creating event
zendesk/volunteer_portal pull request #116
Opened 2018-12-05 06:15 UTC by samzx

Create new event type if doesn't exist before creating event
Resolves #112 

## Description
As an admin creating an event, I expect a new Event type to be created if it doesn’t already exist

## References
[Github Issue](https://github.com/zendesk/volunteer_portal/issues/112)

## Implementation notes (if needed)
Refactored event type creation to be re-used.

## Tasks (if needed)
- [ ] Write tests ?

## Screenshots (if needed)
<details>
<summary>Event type is now an autocomplete field</summary>
<img width="493" alt="screen shot 2018-12-05 at 5 06 18 pm" src="https://user-images.githubusercontent.com/27116427/49493435-3e6c0800-f8b0-11e8-9204-7b8200414657.png">
</details>

<details>
<summary>Event Created</summary>
<img width="957" alt="screen shot 2018-12-05 at 5 06 49 pm" src="https://user-images.githubusercontent.com/27116427/49493436-3e6c0800-f8b0-11e8-9dbb-e813f7ed2eed.png">
</details>

<details>
<summary>Event Type Also Created</summary>
<img width="1000" alt="screen shot 2018-12-05 at 5 07 05 pm" src="https://user-images.githubusercontent.com/27116427/49493437-3e6c0800-f8b0-11e8-892a-8efac88f4c41.png">
</details>

## CCs

If app migration related
@zendesk/volunteer

Anyone specific?

## Risks (if any)
* [HIGH | medium | low] - low

2018-12-20 00:35 UTC, xuebingli requested changes
Thanks for the PR, Sam! I like the minimalist approach. I'd like to suggest one code change and one design change.

This PR assumes that an event type can be uniquely identified by its name, while currently the backend does not have this validation in place. I suppose we should add such validation of `title` on `EventType` on the backend.

Correct me if I'm wrong. In case of non-existing event type, the frontend would make two requests - one to create the event type and the other to create the event. I reckon only one request is needed if the request contains event type name instead of event type id. ActiveRecord has a handy `find_or_create_by` method. This method could help us find or create event type in one go during event creation. I'm happy to show you how it works. Let's pair in the next volunteer engineering session.

2019-04-10 07:19 UTC, xuebingli commented
@samzx Here's a POC. Hope you find it helpful. https://github.com/zendesk/volunteer_portal/compare/master...xli/issue-112-poc

2019-04-10 23:42 UTC, samzx commented
We can use these two branches as a POC for organisations.

2019-05-22 06:20 UTC, samzx commented
Going to close this for now. Will re-open when worked on again. Low priority.

2019-05-22 06:20 UTC, closed without merging