Ensure end time is after start time
zendesk/volunteer_portal pull request #37
Opened 2018-07-18 04:59 UTC by yifeiwu

Ensure end time is after start time for an event.

2018-07-18 05:29 UTC, xuebingli approved these changes
👍 assuming that time only flows in one direction and that very direction is forward :trollface:

2018-07-18 05:29 UTC, xuebingli approved these changes
👍 assuming that time only flows in one direction and that very direction is forward :trollface:

2018-07-18 06:32 UTC, yifeiwu commented
Go home Dr Strange, you're drunk

2018-07-18 06:55 UTC, nchieng approved these changes

2018-07-18 15:58 UTC, ragurney approved these changes

2018-07-18 20:16 UTC, craig-day requested changes
please add a server side validation too

2018-09-16 22:47 UTC, yifeiwu commented
@craig-day added server side tests

2018-10-10 01:32 UTC, xuebingli commented
@craig-day 💇‍♂️

2018-10-10 01:53 UTC, craig-day approved these changes

2018-10-10 01:53 UTC, craig-day commented on app/models/event.rb
> +    errors.add(:users, "total can't be above capacity") if capacity && users.size > capacity
don't love this style change, the line is pretty long now.

2018-10-10 01:53 UTC, craig-day commented on app/models/event.rb
> +    errors.add(:ends_at, "should not end before it starts") if starts_at && ends_at && ends_at <= starts_at
I would prefer an if block, not a trailing if when its this long.

2018-10-24 00:53 UTC, merged